version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  datamanagment:
    build:
      context: ./datamanagement-service
      dockerfile: Dockerfile
    #environment:
    #  - "SPRING_CONFIG_LOCATION=./datamanagement-service/tmp/main/resources"
    ports:
      - "8080:8080"