version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - shared_data:/app/share

  datamanagement:
    build:
      context: ./datamanagement-service
      dockerfile: Dockerfile
    expose:
      - "8080"
    volumes:
      - shared_data:/app/share

volumes:
  shared_data:
