version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  datamanagment:
    build:
      context: ./datamanagement-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"