export const json = [
  { id: 1, name: "Zentis" },
  { id: 2, name: "Babor Kosmetik" },
  { id: 3, name: "RWTH Aachen" },
  { id: 4, name: "Aldi" },
  { id: 5, name: "Bauhaus" },
  { id: 6, name: "Sparkasse Aachen" },
  { id: 7, name: "Api Computerhandels GmbH" },
  { id: 8, name: "Debeka" },
  { id: 9, name: "Steuerberaterkammer Köln" },
  { id: 10, name: "Rechtsanwaltsberufe" },
  { id: 11, name: "Notarberufe" },
  { id: 12, name: "Spedition Hammer Advanced Logistics" },
  { id: 13, name: "Inform" },
  { id: 14, name: "Auto Thüllen" },
  { id: 15, name: "StädteRegion Aachen" },
  { id: 16, name: "Finanzamt" },
  { id: 17, name: "Finanzamt" },
  { id: 18, name: "Zoll Aachen" },
  { id: 19, name: "Polizei" },
  { id: 20, name: "Feuerwehr Aachen" },
  { id: 21, name: "OGS/ Kita" },
  { id: 22, name: "FH Aachen - Studienberatung" },
  { id: 23, name: "RWTH-Studienberatung" },
  { id: 24, name: "Lehramt Berufskolleg" },
  { id: 25, name: "Soziale Arbeit" },
  { id: 26, name: "BWL, Wirtschaftsrecht und Global Business and Economics" },
  { id: 27, name: "EVA" },
];
